/* =========================================================
   RETAIL SALES ANALYTICS PROJECT
   SQL Server Portfolio Project

   SECTION 1: DATABASE SETUP
   Purpose: Create the database and tables used for analysis.
   ========================================================= */

CREATE DATABASE RetailSalesAnalytics;
USE RetailSalesAnalytics;
CREATE TABLE Customers (
CustomerID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100),
City VARCHAR(50),
State VARCHAR(50),
JoinDate DATE
);
CREATE TABLE Products ( 
ProductID INT PRIMARY KEY,
ProductName VARCHAR(100),
Category VARCHAR(50),
UnitPrice DECIMAL(10,2)
);
CREATE TABLE Orders (
OrderID INT PRIMARY KEY,
CustomerID INT,
OrderDate DATE,
OrderStatus VARCHAR(20),
FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
CREATE TABLE OrderDetails ( 
OrderDetailID INT PRIMARY KEY, 
OrderID INT,
ProductID INT,
Quantity INT,
UnitPrice DECIMAL (10,2), 
FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
/* =========================================================
   DATASET INFORMATION

   Tables: Customers, Products, Orders, OrderDetails
   Data Loading: Dataset imported into SQL Server using
   SQL Server Object Explorer/import tools.
   ========================================================= */

/* =========================================================
   SECTION 2: DATA ANALYSIS
   Purpose: Analyze customers, sales, and product performance.
   ========================================================= */

/* =========================================================
   BUSINESS QUESTION 1: CUSTOMER DISTRIBUTION

   Which states have the largest customer base?
   ========================================================= */

SELECT
    State,
    COUNT(*) AS CustomerCount
FROM Customers
GROUP BY State
ORDER BY CustomerCount DESC;

/* =========================================================
   BUSINESS QUESTION 2: CUSTOMER ACQUISITION TREND

   How many new customers joined each year?
   ========================================================= */

SELECT
    YEAR(JoinDate) AS JoinYear,
    COUNT(*) AS NewCustomers
FROM Customers
GROUP BY YEAR(JoinDate)
ORDER BY JoinYear;

/* =========================================================
   BUSINESS QUESTION 3: OVERALL SALES PERFORMANCE

   What is the total revenue generated by the business?
   ========================================================= */

SELECT
    SUM(Quantity * UnitPrice) AS TotalRevenue
FROM OrderDetails;

/* =========================================================
   BUSINESS QUESTION 4: MONTHLY SALES TREND

   How did sales revenue change month by month in 2026?
   ========================================================= */

SELECT
    MONTH(o.OrderDate) AS OrderMonth,
    SUM(od.Quantity * od.UnitPrice) AS MonthlyRevenue
FROM Orders o
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
WHERE YEAR(o.OrderDate) = 2026
GROUP BY MONTH(o.OrderDate)
ORDER BY OrderMonth;

/* =========================================================
   BUSINESS QUESTION 5: CATEGORY PERFORMANCE

   Which product categories generate the most revenue?
   ========================================================= */

SELECT
    p.Category,
    SUM(od.Quantity * od.UnitPrice) AS CategoryRevenue
FROM OrderDetails od
JOIN Products p
    ON od.ProductID = p.ProductID
GROUP BY p.Category
ORDER BY CategoryRevenue DESC;

/* =========================================================
   BUSINESS QUESTION 6: PRODUCT PERFORMANCE

   Which 10 products generate the most revenue?
   ========================================================= */

SELECT TOP 10
    p.ProductID,
    p.ProductName,
    p.Category,
    SUM(od.Quantity * od.UnitPrice) AS ProductRevenue
FROM Products p
JOIN OrderDetails od
    ON p.ProductID = od.ProductID
GROUP BY p.ProductID, p.ProductName, p.Category
ORDER BY ProductRevenue DESC;

/* =========================================================
   BUSINESS QUESTION 7: TOP CUSTOMERS

   Which customers generate the most revenue for the business?
   ========================================================= */

SELECT TOP 10
    c.CustomerID,
    c.FirstName,
    c.LastName,
    SUM(od.Quantity * od.UnitPrice) AS CustomerRevenue
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY CustomerRevenue DESC;

/* =========================================================
   BUSINESS QUESTION 8: CUSTOMER SEGMENTATION

   How can customers be classified based on their total spending?
   ========================================================= */

WITH CustomerTotals AS
(
    SELECT
        c.CustomerID,
        c.FirstName,
        c.LastName,
        SUM(od.Quantity * od.UnitPrice) AS CustomerRevenue
    FROM Customers c
    JOIN Orders o
        ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od
        ON o.OrderID = od.OrderID
    GROUP BY c.CustomerID, c.FirstName, c.LastName
)

SELECT
    CustomerID,
    FirstName,
    LastName,
    CustomerRevenue,
    CASE
        WHEN CustomerRevenue >= 7000 THEN 'High Value'
        WHEN CustomerRevenue >= 3000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS CustomerSegment
FROM CustomerTotals
ORDER BY CustomerRevenue DESC;

/* =========================================================
   BUSINESS QUESTION 9: AVERAGE ORDER VALUE

   What is the average amount customers spend per order?
   ========================================================= */

SELECT
    AVG(OrderTotal) AS AverageOrderValue
FROM
(
    SELECT
        o.OrderID,
        SUM(od.Quantity * od.UnitPrice) AS OrderTotal
    FROM Orders o
    JOIN OrderDetails od
        ON o.OrderID = od.OrderID
    GROUP BY o.OrderID
) AS OrderTotals;

/* =========================================================
   BUSINESS QUESTION 10: TOP PRODUCT BY CATEGORY

   Which product generates the highest revenue
   within each product category?
   ========================================================= */

WITH ProductSales AS
(
    SELECT
        p.ProductID,
        p.ProductName,
        p.Category,
        SUM(od.Quantity * od.UnitPrice) AS TotalSales
    FROM Products p
    JOIN OrderDetails od
        ON p.ProductID = od.ProductID
    GROUP BY p.ProductID, p.ProductName, p.Category
),
RankedProducts AS
(
    SELECT
        ProductID,
        ProductName,
        Category,
        TotalSales,
        RANK() OVER
        (
            PARTITION BY Category
            ORDER BY TotalSales DESC
        ) AS CategoryRank
    FROM ProductSales
)

SELECT *
FROM RankedProducts
WHERE CategoryRank = 1;